import asyncio
import os
import sys
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# Ensure `backend/` (the parent of this `alembic/` directory) is importable
# regardless of the working directory the `alembic` CLI happens to be
# invoked from, so `core.config` and `db.base` resolve exactly like they do
# for the rest of the application.
BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from core.config import settings  # noqa: E402
from db.base import Base  # noqa: E402

# Import the models package so every model class registers itself on
# `Base.metadata` before autogenerate compares it against the database.
# `db/base.py` intentionally defines no models itself (see its docstring),
# so this import is required for `target_metadata` below to be non-empty -
# without it, autogenerate would see an empty metadata and generate DROP
# statements for every existing table.
from db import models  # noqa: E402,F401

# GeoAlchemy2's own Alembic helpers (recommended by its docs for exactly
# this setup): `render_item`/`writer` make autogenerated migrations for
# Geometry/Geography columns include their `from geoalchemy2 import ...`
# import and skip re-declaring the spatial index GeoAlchemy2 already
# manages via DDL events, and `include_object` excludes PostGIS's own
# internal tables (e.g. `spatial_ref_sys`) from the diff. Discovered as
# necessary while generating the first migration for the PostGIS-backed
# models in db/models/ - without these, autogenerate produced a migration
# missing a required import and proposed dropping `spatial_ref_sys`.
from geoalchemy2.alembic_helpers import include_object  # noqa: E402
from geoalchemy2.alembic_helpers import render_item  # noqa: E402
from geoalchemy2.alembic_helpers import writer as geoalchemy2_writer  # noqa: E402

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Use the application's own DATABASE_URL from Pydantic Settings as the single
# source of truth, instead of maintaining a second copy in alembic.ini.
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Base.metadata is what Alembic uses for 'autogenerate' support. The
# `db.models` import above ensures every model already registered its
# table on this metadata; further models added under db/models/ later only
# need to be imported from db/models/__init__.py - no further env.py
# changes will be needed then.
target_metadata = Base.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        render_item=render_item,
        process_revision_directives=geoalchemy2_writer,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        render_item=render_item,
        process_revision_directives=geoalchemy2_writer,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""

    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
