"""add realtime simulation models

Revision ID: 136e034f7a89
Revises: adc957f6e9e5
Create Date: 2026-08-15 05:46:33.515669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136e034f7a89'
down_revision: Union[str, Sequence[str], None] = 'adc957f6e9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fleet_number', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fleet_number')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'active', 'completed', 'cancelled')", name='ck_trips_status'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_route_id'), 'trips', ['route_id'], unique=False)
    op.create_index('ix_trips_route_id_status', 'trips', ['route_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_table('stop_times',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_offset_s', sa.Integer(), nullable=False),
    sa.Column('departure_offset_s', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('departure_offset_s >= arrival_offset_s', name='ck_stop_times_departure_not_before_arrival'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'sequence', name='uq_stop_times_trip_id_sequence')
    )
    op.create_index(op.f('ix_stop_times_stop_id'), 'stop_times', ['stop_id'], unique=False)
    op.create_index(op.f('ix_stop_times_trip_id'), 'stop_times', ['trip_id'], unique=False)
    op.create_table('vehicle_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_stop_id', sa.UUID(), nullable=True),
    sa.Column('next_stop_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('not_started', 'en_route', 'at_stop', 'completed')", name='ck_vehicle_positions_status'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_vehicle_positions_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_vehicle_positions_longitude_range'),
    sa.ForeignKeyConstraint(['current_stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['next_stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_positions_trip_id'), 'vehicle_positions', ['trip_id'], unique=False)
    op.create_index(op.f('ix_vehicle_positions_vehicle_id'), 'vehicle_positions', ['vehicle_id'], unique=False)
    op.create_index('ix_vehicle_positions_vehicle_id_recorded_at', 'vehicle_positions', ['vehicle_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_positions_vehicle_id_recorded_at', table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_vehicle_id'), table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_trip_id'), table_name='vehicle_positions')
    op.drop_table('vehicle_positions')
    op.drop_index(op.f('ix_stop_times_trip_id'), table_name='stop_times')
    op.drop_index(op.f('ix_stop_times_stop_id'), table_name='stop_times')
    op.drop_table('stop_times')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index('ix_trips_route_id_status', table_name='trips')
    op.drop_index(op.f('ix_trips_route_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
