"""add users, fare_rules, tickets tables

Hand-written (not autogenerated): db/models/user.py, db/models/fare.py,
and db/models/ticket.py are deliberately NOT imported from
db/models/__init__.py (that shared registration file is out of scope for
this workstream to modify - see this project's ownership boundaries), so
`alembic/env.py`'s `target_metadata` doesn't see them and `--autogenerate`
would not pick them up. Column definitions below are written to match
those model files exactly; keep them in sync by hand if either changes.

INTEGRATION NOTE: originally chained directly on top of `adc957f6e9e5`
(the sole head at the time this workstream was developed), since this
migration is unrelated to (does not create/alter) anything the realtime/
simulation workstream (`136e034f7a89`, also based on `adc957f6e9e5`)
touches - the two migrations create entirely disjoint sets of tables with
no foreign keys between them. At integration time this migration was
rebased onto `136e034f7a89` (rather than left as a second head requiring
an `alembic merge`) precisely because there is no real dependency to
reconcile: a straight linear chain adc957f6e9e5 -> 136e034f7a89 ->
4795c429e65f is simpler than an unnecessary merge revision and preserves
a single linear history. This migration's own up/downgrade bodies were
not changed - only `down_revision` below.

Revision ID: 4795c429e65f
Revises: 136e034f7a89
Create Date: 2026-08-15 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4795c429e65f"
down_revision: Union[str, Sequence[str], None] = "136e034f7a89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="passenger", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "fare_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_fare", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "per_leg_fare", sa.Numeric(precision=10, scale=2), server_default="0", nullable=False
        ),
        sa.Column("currency", sa.String(length=3), server_default="PKR", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticket_code", sa.String(length=12), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("fare_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="PKR", nullable=False),
        sa.Column("objective", sa.String(length=30), nullable=False),
        sa.Column("origin_lat", sa.Float(), nullable=False),
        sa.Column("origin_lon", sa.Float(), nullable=False),
        sa.Column("destination_lat", sa.Float(), nullable=False),
        sa.Column("destination_lon", sa.Float(), nullable=False),
        sa.Column("ride_leg_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("transfer_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_duration_s", sa.Float(), nullable=True),
        sa.Column("total_walk_m", sa.Float(), nullable=True),
        sa.Column("route_summary", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_by", sa.UUID(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["validated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_code"),
    )
    op.create_index(op.f("ix_tickets_ticket_code"), "tickets", ["ticket_code"], unique=True)
    op.create_index(op.f("ix_tickets_user_id"), "tickets", ["user_id"], unique=False)

    # Seed the configurable default fare rule referenced by
    # ticketing/fares/config.py, so a fresh environment that has actually
    # run migrations has one active FareRule row rather than only ever
    # relying on the in-code fallback.
    op.execute(
        """
        INSERT INTO fare_rules (id, name, base_fare, per_leg_fare, currency, is_active, created_at, updated_at)
        VALUES (gen_random_uuid(), 'default', 50.00, 20.00, 'PKR', true, now(), now())
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_tickets_user_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_ticket_code"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_table("fare_rules")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
